'use strict';
let lang='th',config,invite=new URLSearchParams(location.hash.slice(1)).get('invite')||'',profile={name:'',affiliation:'',bio:''},photo='',preview='',hasPhoto=false,office='',locked=false,demo=false,busy=false;
if(location.hash)history.replaceState(null,'',location.pathname);
const $=id=>document.getElementById(id),t=(th,en)=>lang==='th'?th:en;
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n}
function message(text){$('notice').textContent=text;$('notice').hidden=!text;if(text)$('notice').focus()}
async function request(route,data){const r=await fetch(config.apiBase+route,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({invite,...data}),signal:AbortSignal.timeout(30000)});const result=await r.json();if(!r.ok){const errors={invalid_invite:t('ลิงก์ไม่ถูกต้องหรือหมดอายุ กรุณาติดต่อผู้จัด','Invalid or expired invitation. Contact the organizer.'),invalid_photo:t('กรุณาเลือกรูป JPG/PNG ไม่เกิน 5 MB และ 20 ล้านพิกเซล','Use a JPG/PNG image up to 5 MB and 20 megapixels.'),closed:t('ปิดรับการแก้ไขข้อมูลแล้ว','Profile editing has closed.'),invalid_office:t('กรุณาเลือกตำแหน่งที่เปิดรับสมัคร','Choose an available position.'),invalid_profile:t('กรุณากรอกข้อมูลให้ครบและยินยอมเผยแพร่','Complete the fields and consent to publication.'),rate_limited:t('กรุณารอสักครู่แล้วลองใหม่','Please wait a minute and retry.')};throw Error(errors[result.error]||t('ส่งไม่สำเร็จ กรุณาลองใหม่','Submission failed. Please retry.'))}return result}
function render(){
 document.documentElement.lang=lang;$('language').textContent=t('English','ภาษาไทย');$('subtitle').textContent=t('รูปและประวัติผู้สมัคร','Candidate photo and biography');$('mode').textContent=demo?t('แบบทดลอง • ข้อมูลและรูปจะไม่ถูกส่งหรือบันทึก','PREVIEW • Information and photos are not sent or saved.'):!config?.apiBase?t('กำลังเตรียมระบบ • ยังไม่เปิดรับข้อมูลผู้สมัคร','In preparation • Candidate submissions are not open.'):t('ข้อมูลจะเผยแพร่หลังกรรมการสรรหาตรวจและคณะกรรมการบริหารเห็นชอบ','Profiles require Nominating Committee review and Executive Committee approval before publication.');
 const root=$('content');root.replaceChildren();
 if(!demo&&(!config?.apiBase||!invite)){const p=el('section',undefined,'panel');p.append(el('h2',t('สำหรับผู้สมัคร','For candidates')),el('p',t('ผู้จัดจะส่งลิงก์ส่วนตัวให้ผู้สมัครแต่ละคน ใช้ลิงก์นั้นเพื่อส่งรูปและประวัติสำหรับหน้าบัตรเลือกตั้ง','The organizer will email each candidate a personal link to submit their photo and biography for the ballot.')));const b=el('button',t('ดูตัวอย่างแบบฟอร์ม','Preview the form'),'button');b.onclick=()=>{demo=true;render()};p.append(b);root.append(p);return}
 const form=el('form',undefined,'panel');form.append(el('h2',t('ข้อมูลผู้สมัคร','Your profile')));if(locked){form.append(el('p',t('ปิดรับแก้ไขแล้ว กรุณาติดต่อผู้จัด','Editing has closed. Contact the organizer.')));root.append(form);return}
 const officeLabel=el('label',t('ตำแหน่งที่สมัคร','Position applied for'));officeLabel.htmlFor='office';const select=el('select');select.id='office';select.required=true;const placeholder=el('option',t('กรุณาเลือกตำแหน่ง','Select a position'));placeholder.value='';placeholder.disabled=true;select.append(placeholder);for(const o of config.offices){const option=el('option',o[lang]);option.value=o.id;select.append(option)}select.value=office;select.onchange=()=>office=select.value;form.append(officeLabel,select);
 for(const [key,th,en,max] of [['name','ชื่อและนามสกุล','Full name',150],['affiliation','สังกัด / หลักสูตร','Affiliation / program',200],['bio','ประวัติและแนวทางทำงาน (ไม่เกิน 3,000 ตัวอักษร)','Biography and plans (up to 3,000 characters)',3000]]){const l=el('label',t(th,en));l.htmlFor=key;const input=el(key==='bio'?'textarea':'input');if(key!=='bio')input.type='text';else input.rows=7;input.id=key;input.required=true;input.maxLength=max;input.value=profile[key];input.oninput=()=>profile[key]=input.value;form.append(l,input)}
 const label=el('label',t('รูปผู้สมัคร JPG/PNG ไม่เกิน 5 MB','Candidate photo JPG/PNG up to 5 MB'));label.htmlFor='photo';const file=el('input');file.type='file';file.id='photo';file.accept='image/jpeg,image/png';file.required=!hasPhoto&&!photo;const img=el('img');img.id='photo-preview';img.alt=t('รูปที่เลือก','Selected photo');img.hidden=!preview;if(preview)img.src=preview;
 file.onchange=async()=>{const f=file.files[0];if(!f)return;if(!['image/jpeg','image/png'].includes(f.type)||f.size>5*1024*1024){file.value='';message(t('เลือกรูป JPG/PNG ไม่เกิน 5 MB','Choose a JPG/PNG up to 5 MB'));return}busy=true;send.disabled=true;try{const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(f)});preview=data;photo=data.split(',')[1];img.src=data;img.hidden=false;message('')}catch{message(t('อ่านรูปไม่ได้ กรุณาเลือกใหม่','Could not read the image. Please choose again.'))}finally{busy=false;send.disabled=false}};
 form.append(label,file,img);if(hasPhoto&&!photo)form.append(el('p',t('มีรูปที่ส่งไว้แล้ว เลือกรูปใหม่ได้หากต้องการเปลี่ยน','A photo is already on file. Choose another to replace it.'),'muted'));
 const consent=el('label',undefined,'consent'),checkbox=el('input');checkbox.type='checkbox';checkbox.required=true;checkbox.id='consent';consent.append(checkbox,el('span',t('ยินยอมให้เผยแพร่ชื่อ รูป และประวัติบนหน้าการเลือกตั้งของ Thailand Section','I consent to publishing my name, photo, and biography on the Thailand Section election page.')));form.append(consent);const send=el('button',demo?t('ทดลองส่งข้อมูล','Try submission'):t('ส่งให้ผู้จัดตรวจรับ','Submit for review'),'button');send.type='submit';form.append(send);form.onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;send.disabled=true;try{if(!demo)await request('/candidate/submit',{...profile,office,photo,consent:checkbox.checked});root.replaceChildren(el('section',demo?t('ทดลองเสร็จแล้ว ไม่มีการส่งหรือบันทึกข้อมูล','Preview complete. No information was sent or saved.'):t('ส่งข้อมูลแล้ว อยู่ระหว่างรอผู้จัดตรวจรับ เปิดลิงก์เดิมอีกครั้งเพื่อแก้ไขได้ก่อนเปิดลงคะแนน','Profile submitted for review. Reopen your invitation to edit before voting opens.'),'panel'));profile={name:'',affiliation:'',bio:''};photo='';preview=''}catch(err){message(err.message||t('ยังยืนยันการส่งไม่ได้ กรุณาลองใหม่','Could not confirm submission. Please retry.'))}finally{busy=false;send.disabled=false}};root.append(form)
}
$('language').onclick=()=>{if(busy)return;lang=lang==='th'?'en':'th';render()};
(async()=>{try{const response=await fetch('config.json',{cache:'no-store'});if(!response.ok)throw Error();config=await response.json();if(invite&&config.apiBase){const u=new URL(config.apiBase);if(u.protocol!=='https:'&&!['localhost','127.0.0.1'].includes(u.hostname))throw Error();const r=await request('/candidate/profile',{});profile=r.profile;hasPhoto=r.hasPhoto;office=r.office?.id||'';config.offices=r.offices||config.offices;locked=r.locked}render()}catch(e){$('content').textContent=t('โหลดแบบฟอร์มไม่ได้ กรุณาติดต่อผู้จัด','Could not load the form. Contact the organizer.');message(e.message)}})();
