'use strict';
let lang='th',config,preview=false,kind='self',formData={};
const $=id=>document.getElementById(id),t=(th,en)=>lang==='th'?th:en;
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n}
function message(text){$('notice').textContent=text;$('notice').hidden=!text;if(text)$('notice').focus()}
function link(href,th,en){const a=el('a',t(th,en),'candidate-link');a.href=href;return a}
function render(){document.documentElement.lang=lang;$('language').textContent=t('English','ภาษาไทย');$('subtitle').textContent=t('ร่วมเสนอชื่อทีมบริหารชุดใหม่','Nominate the next Section leadership');const live=Boolean(config.apiBase&&config.nominationsOpen);$('mode').textContent=preview?t('แบบทดลอง • ไม่มีการส่งหรือบันทึกข้อมูล','PREVIEW • No information is sent or saved.'):live?t('เปิดรับการเสนอชื่อ • ผู้สมัครต้องยืนยันความยินยอมก่อนประกาศ','Nominations open • Candidates must give consent before announcement.'):t('เตรียมการเลือกตั้ง • ยังไม่เปิดรับการเสนอชื่อจริง','Election preparation • Nominations are not open.');const root=$('content');root.replaceChildren();
 const flow=el('section',undefined,'panel');flow.append(el('h2',t('จากการเสนอชื่อถึงประกาศผู้สมัคร','From nomination to announcement')));const steps=el('ol');[["เสนอชื่อหรือสมัครด้วยตนเอง","Nominate someone or apply yourself"],["ผู้สมัครเลือกตำแหน่ง ส่งรูปและประวัติ พร้อมยืนยันความยินยอม","Candidate chooses a position and submits a photo, biography, and consent"],["กรรมการสรรหาตรวจคุณสมบัติและความยินยอม","Nominating Committee checks eligibility and consent"],["คณะกรรมการบริหารเห็นชอบก่อนประกาศและเตรียมบัตรเลือกตั้ง","Executive Committee approval precedes announcement and ballot preparation"]].forEach(([th,en])=>steps.append(el('li',t(th,en))));flow.append(steps);root.append(flow);
 const grid=el('div',undefined,'grid');config.offices.forEach(o=>{const card=el('section',undefined,'panel');card.append(el('h3',o[lang]),el('p',o.type==='APPROVAL'?t('กรรมการทั่วไปอย่างน้อย 2 คน • บัตรเดิมใช้ Yes / No / Abstain แยกคน','At least 2 Members-at-Large • Existing ballot uses Yes / No / Abstain per candidate'):t('ตำแหน่งละ 1 คน','1 seat'),'muted'));grid.append(card)});root.append(grid);
 if(!live&&!preview){const b=el('button',t('ทดลองแบบฟอร์มเสนอชื่อ','Preview nomination form'),'button');b.onclick=()=>{preview=true;render()};root.append(b)}
 if(live||preview){const form=el('form',undefined,'panel');form.style.marginTop='24px';form.append(el('h2',t('เสนอชื่อผู้สมัคร','Candidate nomination')));const label=el('label',t('ประเภทการเสนอชื่อ','Nomination type'));label.htmlFor='kind';const select=el('select');select.id='kind';[['self','สมัครด้วยตนเอง','Self-nomination'],['nominate','เสนอชื่อบุคคลอื่น','Nominate someone else']].forEach(([v,th,en])=>{const o=el('option',t(th,en));o.value=v;select.append(o)});select.value=kind;select.onchange=()=>{kind=select.value;render()};form.append(label,select);
 const fields=[['name','ชื่อผู้สมัคร','Candidate name','text'],['email','อีเมลผู้สมัคร','Candidate email','email']];if(kind==='nominate')fields.push(['nominatorName','ชื่อผู้เสนอ','Nominator name','text'],['nominatorEmail','อีเมลผู้เสนอ','Nominator email','email']);fields.forEach(([key,th,en,type])=>{const l=el('label',t(th,en));l.htmlFor=key;const input=el('input');input.id=key;input.type=type;input.maxLength=type==='email'?254:150;input.required=true;input.value=formData[key]||'';input.oninput=()=>formData[key]=input.value;form.append(l,input)});
 const ol=el('label',t('ตำแหน่งที่เสนอสมัคร','Proposed position'));ol.htmlFor='office';const offices=el('select');offices.id='office';offices.required=true;const placeholder=el('option',t('กรุณาเลือกตำแหน่ง','Select a position'));placeholder.value='';placeholder.disabled=true;offices.append(placeholder);config.offices.forEach(o=>{const option=el('option',o[lang]);option.value=o.id;offices.append(option)});offices.value=formData.office||'';offices.onchange=()=>formData.office=offices.value;form.append(ol,offices);
 const consent=el('label',undefined,'consent'),check=el('input');check.type='checkbox';check.required=true;consent.append(check,el('span',t('ยินยอมให้ใช้ข้อมูลนี้เพื่อติดต่อเรื่องการเสนอชื่อ โดยยังไม่เผยแพร่ข้อมูลผู้สมัคร','I agree to using this information to contact the parties about this nomination. Candidate information will not yet be published.')));form.append(consent);form.append(el('p',t('การเสนอชื่อบุคคลอื่นยังไม่ถือว่าผู้นั้นตอบรับสมัคร ผู้จัดจะติดต่อให้ยืนยันด้วยตนเอง','Nominating someone does not establish their acceptance. The organizer will contact the candidate for confirmation.'),'muted'));
 const send=el('button',preview?t('ทดลองส่งการเสนอชื่อ','Try submission'):t('ส่งการเสนอชื่อ','Submit nomination'),'button');send.type='submit';form.append(send);form.onsubmit=async e=>{e.preventDefault();send.disabled=true;try{if(!preview){const r=await fetch(config.apiBase+'/nominations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...formData,kind,contactConsent:check.checked}),signal:AbortSignal.timeout(20000)});if(!r.ok)throw Error()}form.replaceChildren(el('h2',preview?t('ทดลองเสร็จแล้ว ไม่มีการส่งข้อมูล','Preview complete. No information was sent.'):t('ได้รับการเสนอชื่อแล้ว','Nomination received')),el('p',preview?t('เมื่อเปิดรับจริง ผู้จัดจะติดต่อผู้สมัครเพื่อยืนยันและส่งลิงก์ส่วนตัวให้กรอกประวัติ','During live nominations, the organizer will contact the candidate and provide a personal profile link.'):t('ขั้นต่อไป ผู้จัดจะติดต่อผู้สมัครเพื่อยืนยันและส่งลิงก์ส่วนตัวให้กรอกประวัติ','The organizer will contact the candidate for confirmation and provide a personal profile link.')));formData={};}catch{message(t('ยังส่งไม่ได้ กรุณาตรวจข้อมูลหรือติดต่อผู้จัด','Could not submit. Check the information or contact the organizer.'))}finally{send.disabled=false}};root.append(form)}
 const links=el('section',undefined,'panel');links.style.marginTop='24px';links.append(link('candidate.html','สำหรับผู้สมัคร: ส่งรูปและประวัติ','For candidates: photo and biography'),link('ballot.html','ดูรายชื่อที่ประกาศและตัวอย่างบัตรเลือกตั้ง','Announced candidates and ballot preview'),link('../vote-demo.html','ตัวอย่างบัตรเลือกตั้งเดิม','Original ballot demonstration'));root.append(links);
 const committee=el('section',undefined,'panel');committee.append(el('h2',t('คณะกรรมการสรรหา','Nominating Committee')),el('p',t('รศ.ดร.สุรเทพ เขียวหอม · ศ.ดร.ศิริพร จึงสุทธิวงษ์ · ศ.ดร.พัชณิตา ธรรมยงค์กิจ','Assoc. Prof. Dr. Soorathep Kheawhom · Prof. Dr. Siriporn Jungsuttiwong · Prof. Dr. Patchanita Thamyongkit')));root.append(committee);
}
$('language').onclick=()=>{lang=lang==='th'?'en':'th';render()};
(async()=>{try{const r=await fetch('config.json',{cache:'no-store'});if(!r.ok)throw Error();config=await r.json();render()}catch{$('content').textContent=t('โหลดข้อมูลไม่ได้ กรุณาลองใหม่ภายหลัง','Could not load election information. Please try again later.')}})();
