CREATE TABLE members(id TEXT PRIMARY KEY,name TEXT NOT NULL,email TEXT NOT NULL UNIQUE,token_hash TEXT NOT NULL UNIQUE,expires INTEGER NOT NULL,active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE posts(id TEXT PRIMARY KEY,owner TEXT NOT NULL REFERENCES members(id),kind TEXT NOT NULL,body TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',revision INTEGER NOT NULL DEFAULT 1,created INTEGER NOT NULL,updated INTEGER NOT NULL,reason TEXT NOT NULL DEFAULT '');
CREATE INDEX posts_status ON posts(status,kind);
CREATE TABLE access_requests(email TEXT PRIMARY KEY,name TEXT NOT NULL,created INTEGER NOT NULL);
CREATE TABLE reports(id TEXT PRIMARY KEY,post_id TEXT NOT NULL,reason TEXT NOT NULL,created INTEGER NOT NULL,resolved INTEGER NOT NULL DEFAULT 0);
CREATE TABLE audit(id INTEGER PRIMARY KEY AUTOINCREMENT,action TEXT NOT NULL,post_id TEXT,created INTEGER NOT NULL);
CREATE TABLE limits(key TEXT PRIMARY KEY,window INTEGER NOT NULL,count INTEGER NOT NULL);
