'use strict';
let config, lang='th', step=0, choices={}, token='', sending=false, receipt='';
const $=id=>document.getElementById(id), txt=(th,en)=>lang==='th'?th:en;
function node(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function button(text,fn,secondary=false){const n=node('button',text,'button'+(secondary?' secondary':''));n.type='button';n.onclick=fn;return n;}
function notice(message){$('notice').textContent=message;$('notice').hidden=!message;if(message)$('notice').focus();}
function intro(title,description){const n=node('div',undefined,'intro');n.append(node('h2',title),node('p',description,'muted'));return n;}
function go(n){step=n;notice('');render();$('content').setAttribute('tabindex','-1');$('content').focus();}
function complete(){return config.offices.every(o=>Object.hasOwn(choices,o.id));}
function chosen(o){return choices[o.id]==='ABSTAIN'?txt('งดออกเสียง','Abstain'):o.candidates.find(c=>c.id===choices[o.id])?.name||'';}
function render(){
 $('language').textContent=txt('English','ภาษาไทย');document.documentElement.lang=lang;
 $('chapter').textContent=config.chapter;
 $('subtitle').textContent=txt('ร่วมเลือกทีมที่จะขับเคลื่อนกิจกรรมของนักศึกษา','Choose the team to lead your student community');
 $('mode').textContent=config.mode==='demo'?txt('โหมดทดลอง • ผู้สมัครสมมติ ไม่มีการส่งหรือบันทึกคะแนน','DEMO • Fictional candidates. No votes are sent or recorded.'):config.mode==='draft'?txt('เตรียมการเลือกตั้ง • ยังไม่เปิดรับลงคะแนน','Election preparation • Voting is not open'):txt('การเลือกตั้ง • โปรดตรวจสอบข้อมูลก่อนส่งคะแนน','Election • Please review your choices before submitting');
 $('mode').className='banner'+(config.mode==='live'?' live':'');
 $('footerNote').textContent=txt('เลือกหนึ่งคนหรืองดออกเสียงในแต่ละตำแหน่ง','Choose one candidate or abstain for each office.');
 $('steps').replaceChildren();[txt('เลือกผู้สมัคร','Choose'),txt('ตรวจทาน','Review'),txt('เสร็จสิ้น','Complete')].forEach((t,i)=>$('steps').append(node('li',`${i+1}  ${t}`,i===step?'active':'')));
 const root=$('content');root.replaceChildren();
 if(config.mode==='draft'){
 root.append(intro(txt('เตรียมทีมบริหารชุดใหม่','Preparing the next leadership team'),txt('ยังไม่มีรายชื่อผู้สมัครและกำหนดวันเลือกตั้ง เมื่อพร้อมจะแสดงข้อมูลที่หน้านี้','Candidate nominations and election dates have not been announced. Updates will appear here.')));
 const grid=node('div',undefined,'grid');config.offices.forEach((o,i)=>{const p=node('section',undefined,'panel');p.append(node('span',`0${i+1}`,'number'),node('h3',o[lang]),node('p',txt('1 ตำแหน่ง • รอรายชื่อผู้สมัคร','1 seat • Candidates to be announced'),'muted'));grid.append(p)});root.append(grid);
 root.append(button(txt('ทดลองบัตรเลือกตั้ง','Try a sample ballot'),async()=>{try{config=await fetch('sample.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.json()});config.mode='demo';choices={};go(0)}catch{notice(txt('โหลดตัวอย่างไม่ได้ กรุณาลองใหม่','Could not load the sample. Please retry.'))}}));return;}
 if(step===2){const p=node('section',undefined,'panel complete');p.append(node('div','✓','check'),node('h2',config.mode==='demo'?txt('ทดลองเสร็จแล้ว','Preview complete'):txt('บันทึกคะแนนแล้ว','Ballot recorded')),node('p',config.mode==='demo'?txt('ไม่มีการส่งหรือบันทึกคะแนนจากการทดลองนี้','No vote was sent or recorded in this preview.'):txt('ขอบคุณที่ร่วมเลือกทีมบริหารของ Student Chapter','Thank you for choosing your Student Chapter leadership.')));if(receipt)p.append(node('p',txt('รหัสยืนยัน: ','Receipt: ')+receipt,'muted'));if(config.mode==='demo')p.append(button(txt('กลับหน้าการเลือกตั้ง','Back to election'),()=>location.reload()));root.append(p);return;}
 if(step===1){root.append(intro(txt('ตรวจทานก่อนยืนยัน','Review your ballot'),txt('ตรวจสอบตัวเลือกทั้ง 4 ตำแหน่ง สามารถกลับไปแก้ไขก่อนส่งได้','Check all four choices. You can go back to edit before submitting.')));const card=node('div',undefined,'review');config.offices.forEach(o=>{const r=node('div',undefined,'review-row');r.append(node('span',o[lang]),node('strong',chosen(o)));card.append(r)});root.append(card);const actions=node('div',undefined,'actions');actions.append(button(txt('กลับไปแก้ไข','Edit choices'),()=>go(0),true),button(config.mode==='demo'?txt('ยืนยันการทดลอง','Finish preview'):txt('ยืนยันส่งคะแนน','Submit ballot'),submit));root.append(actions);if(config.mode==='live')root.append(node('p',txt('เมื่อส่งสำเร็จแล้วจะเปลี่ยนคะแนนไม่ได้ หากการเชื่อมต่อขัดข้องให้ลองส่งซ้ำด้วยรหัสเดิม','After submission, choices cannot be changed. If the connection fails, retry with the same voting code.'),'muted'));return;}
 root.append(intro(txt('เลือกผู้สมัคร','Choose your candidates'),txt('เลือกหนึ่งคนหรืองดออกเสียงให้ครบทุกตำแหน่ง','Select one candidate or abstain for every office.')));
 if(config.mode==='live'){const panel=node('div',undefined,'panel');const label=node('label',txt('รหัสลงคะแนนที่ได้รับจากผู้จัด','Voting code from the organizer'));label.htmlFor='voter-code';const input=node('input');input.id='voter-code';input.type='password';input.autocomplete='off';input.value=token;input.oninput=()=>token=input.value.trim();panel.append(label,input,node('p',txt('รหัสใช้ส่งคะแนนได้หนึ่งครั้ง โปรดเก็บเป็นความลับ','Your code can submit one ballot. Keep it private.'),'muted'));root.append(panel);}
 const form=node('form');const grid=node('div',undefined,'grid');config.offices.forEach((o,i)=>{const field=node('fieldset',undefined,'office'),legend=node('legend');legend.append(node('span',`OFFICE 0${i+1}`,'number'),node('strong',o[lang]));field.append(legend);[...o.candidates,{id:'ABSTAIN',name:txt('งดออกเสียง','Abstain')}].forEach(c=>{const label=node('label',undefined,'choice'+(c.id==='ABSTAIN'?' abstain':'')),input=node('input');input.type='radio';input.name=o.id;input.value=c.id;input.required=true;input.checked=choices[o.id]===c.id;input.onchange=()=>{choices[o.id]=c.id;notice('')};const info=node('div');info.append(node('div',c.name,'name'));if(c.affiliation)info.append(node('div',c.affiliation,'muted'));if(c.bio)info.append(node('div',c.bio,'bio'));label.append(input,info);field.append(label)});grid.append(field)});form.append(grid);const actions=node('div',undefined,'actions');actions.append(node('span',txt('ตรวจทานตัวเลือกก่อนส่งคะแนน','Review your choices before submitting'),'muted'));const next=node('button',txt('ตรวจทานบัตรเลือกตั้ง →','Review ballot →'),'button');next.type='submit';actions.append(next);form.append(actions);form.onsubmit=e=>{e.preventDefault();if(config.mode==='live'&&!token){notice(txt('กรุณาระบุรหัสลงคะแนน','Enter your voting code'));return}if(complete())go(1)};root.append(form);
}
async function submit(){if(sending||!complete())return;if(config.mode==='demo'){choices={};go(2);return}sending=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);try{const r=await fetch(config.apiBase+'/ballots',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({electionId:config.electionId,token,choices}),signal:AbortSignal.timeout(20000)});const data=await r.json();if(!r.ok){const errors={closed:txt('ยังไม่เปิดหรือหมดเวลาลงคะแนนแล้ว','Voting is not currently open'),invalid_token:txt('รหัสไม่ถูกต้อง กรุณาติดต่อผู้จัด','Invalid voting code. Contact the organizer.'),invalid_ballot:txt('บัตรไม่ตรงกับการเลือกตั้ง กรุณาโหลดหน้าใหม่','Ballot does not match the election. Reload the page.')};throw Error(errors[data.error]||txt('ส่งคะแนนไม่สำเร็จ กรุณาลองใหม่','Submission failed. Please retry.'))}receipt=data.receipt;choices={};token='';go(2)}catch(e){notice(e.name==='TimeoutError'||e instanceof TypeError?txt('ยังยืนยันผลการส่งไม่ได้ ลองส่งซ้ำด้วยรหัสเดิม ระบบจะไม่เพิ่มบัตรซ้ำ','Submission could not be confirmed. Retry with the same code; the ballot will not be duplicated.'):e.message)}finally{sending=false;document.querySelectorAll('button').forEach(b=>b.disabled=false)}}
$('language').onclick=()=>{lang=lang==='th'?'en':'th';render()};
(async()=>{try{const r=await fetch('config.json',{cache:'no-store'});if(!r.ok)throw Error();config=await r.json();if(config.mode==='live'){const u=new URL(config.apiBase);if(u.protocol!=='https:'&&!['localhost','127.0.0.1'].includes(u.hostname))throw Error();const response=await fetch(config.apiBase+'/election',{cache:'no-store'});if(!response.ok)throw Error();const current=await response.json();if(current.electionId!==config.electionId)throw Error();config={...current,mode:'live',apiBase:config.apiBase};}if(!['draft','demo','live'].includes(config.mode))throw Error();render()}catch{$('content').replaceChildren(node('p',txt('ยังโหลดข้อมูลการเลือกตั้งไม่ได้ กรุณาลองใหม่ภายหลัง','Election information could not be loaded. Please try again later.')))}})();
