'use strict';
let api='',token='';const $=id=>document.getElementById(id),el=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n};
async function req(path,b={}){const r=await fetch(api+'/admin/'+path,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify(b)});const d=await r.json();if(!r.ok)throw Error('ดำเนินการไม่สำเร็จ / Request failed: '+d.error);return d}
function action(label,fn){const b=el('button',label);b.type='button';b.onclick=async()=>{b.disabled=true;try{await fn();$('notice').textContent='บันทึกแล้ว / Saved'}catch(e){$('notice').textContent=e.message}finally{b.disabled=false}};return b}
function card(title){const c=el('article');c.className='card';c.append(el('h3',title));return c}
async function refresh(){const d=await req('list');$('login').hidden=true;const root=$('panel');root.hidden=false;root.replaceChildren();root.append(el('h2','ขอสิทธิ์ลงประกาศ / Access requests'));
 for(const a of d.requests){const c=card(a.name);c.append(el('p',a.email),action('สร้างลิงก์ส่วนตัว / Create private link',async()=>{const r=await req('invite',{name:a.name,email:a.email});const input=el('textarea');input.readOnly=true;input.value=r.link;c.replaceChildren(el('p','คัดลอกส่งให้สมาชิกทางอีเมล ลิงก์อายุ 30 วัน / Copy and send by email; valid for 30 days.'),input);input.select()}));root.append(c)}
 root.append(el('h2','ประกาศ / Posts'));for(const p of d.posts){const body=JSON.parse(p.body),c=card(body.title);c.append(el('p',p.owner_name+' · '+p.kind+' · '+p.status));for(const [key,value] of Object.entries(body)){if(value)c.append(el('p',({institution:'สถาบัน / Institution',location:'สถานที่ / Location',tags:'หัวข้อ / Topics',description:'รายละเอียด / Description',contact:'ติดต่อ / Contact',link:'ลิงก์ / Link',funding:'ทุน / Funding',category:'ประเภท / Category',start:'เริ่ม / Start',end:'สิ้นสุด / End',deadline:'ปิดรับ / Deadline',title:'หัวข้อ / Title'}[key]||key)+': '+value))}const reason=el('textarea');reason.placeholder='เหตุผล / Review note';reason.maxLength=1000;c.append(reason);for(const [state,label] of [['approved','อนุมัติ / Approve'],['rejected','ส่งกลับแก้ไข / Return'],['hidden','ซ่อน / Hide']])c.append(action(label,async()=>{await req('review',{id:p.id,revision:p.revision,status:state,reason:reason.value});await refresh()}));root.append(c)}
 root.append(el('h2','รายงานปัญหา / Reports'));for(const r of d.reports){const c=card(r.post_id);c.append(el('p',r.reason),action('จัดการแล้ว / Resolve',async()=>{await req('resolve',{id:r.id});await refresh()}));root.append(c)}
 root.append(el('h2','สมาชิก / Members'));for(const m of d.members){const c=card(m.name);c.append(el('p',m.email+' · '+(m.active?'Active':'Revoked')),action('ระงับลิงก์ / Revoke',async()=>{await req('revoke',{id:m.id});await refresh()}));root.append(c)}
}
$('login').onsubmit=async e=>{e.preventDefault();token=$('secret').value;$('secret').value='';try{await refresh()}catch(e){token='';$('notice').textContent=e.message}};$('logout').onclick=()=>{token='';$('panel').replaceChildren();$('panel').hidden=true;$('login').hidden=false};
(async()=>{try{api=(await (await fetch('config.json')).json()).apiBase}catch{$('notice').textContent='โหลดไม่สำเร็จ / Could not load configuration'}})();
