'use strict';
let lang='th',kind='opportunity',posts=[],api='',token='',mine=[];
const $=id=>document.getElementById(id),t=(th,en)=>lang==='th'?th:en;
const categories={intern:['ฝึกงาน','Internship'],assistant:['ผู้ช่วยวิจัย','Research assistant'],masters:['ปริญญาโท','Master’s'],phd:['ปริญญาเอก','PhD'],postdoc:['Postdoc','Postdoc'],job:['งาน','Job']};
const kinds={opportunity:['โอกาสวิจัย','Opportunities'],lab:['ทำเนียบแล็บ','Research labs'],event:['ปฏิทินกิจกรรม','Events']};
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n};
const button=(label,fn,secondary=false)=>{const b=el('button',label,secondary?'secondary':'');b.type='button';b.onclick=fn;return b};
function notice(s){$('notice').textContent=s}
async function request(path,body){const r=await fetch(api+path,{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:JSON.stringify(body),signal:AbortSignal.timeout(20000)});const d=await r.json();if(!r.ok)throw Error(d.error==='unauthorized'?t('ลิงก์หมดอายุหรือไม่ถูกต้อง กรุณาติดต่อผู้ดูแล','Link expired or invalid. Contact the administrator.'):d.error==='revision_changed'?t('ข้อมูลเปลี่ยนแล้ว กรุณาโหลดใหม่','This post changed. Reload and try again.'):t('ดำเนินการไม่สำเร็จ กรุณาตรวจข้อมูลหรือลองใหม่ภายหลัง','Could not complete the request. Check the fields or retry later.'));return d}
function workspace(){const w=$('workspace');w.hidden=false;w.replaceChildren();w.focus();return w}
function link(url,label){const a=el('a',label);a.href=url;a.target='_blank';a.rel='noopener noreferrer';return a}
function render(){
 document.documentElement.lang=lang;$('language').textContent=t('English','ภาษาไทย');$('title').textContent=t('พื้นที่เชื่อมต่อชุมชนวิจัย','A place for research connections');$('intro').textContent=t('ค้นหาโอกาสศึกษาต่อ รู้จักห้องวิจัย และร่วมกิจกรรมของเครือข่าย','Find research opportunities, meet research groups, and join community events.');$('contribute').textContent=t('ร่วมลงประกาศ','Contribute');$('mine').textContent=t('ประกาศของฉัน','My posts');$('logout').textContent=t('ออกจากระบบ','Sign out');$('mine').hidden=$('logout').hidden=!token;$('searchLabel').textContent=t('ค้นหา','Search');$('search').placeholder=t('หัวข้อวิจัย สถาบัน เทคนิค…','Research, institution, technique…');$('categoryLabel').textContent=t('ประเภท','Category');$('archiveLabel').textContent=t('รวมประกาศที่ปิดแล้ว','Include archived posts');$('footerNote').textContent=t('ประกาศเผยแพร่หลังผู้ดูแลตรวจรับ โปรดตรวจสอบรายละเอียดกับเจ้าของประกาศ','Posts require administrator review. Confirm details with the posting institution.');
 $('tabs').replaceChildren();for(const [k,v] of Object.entries(kinds)){const b=button(t(...v),()=>{kind=k;render()});b.setAttribute('aria-pressed',String(k===kind));$('tabs').append(b)}
 const previous=$('category').value;$('category').replaceChildren();for(const [k,v] of Object.entries({'':['ทั้งหมด','All'],...(kind==='opportunity'?categories:{})})){const o=el('option',t(...v));o.value=k;$('category').append(o)}$('category').value=previous in categories&&kind==='opportunity'?previous:'';list();
}
function list(){
 const term=$('search').value.toLowerCase(),cat=$('category').value;let items=posts.filter(p=>p.kind===kind&&($('archive').checked||!p.archived)&&(!cat||p.category===cat)&&[p.title,p.institution,p.tags,p.location,p.description].join(' ').toLowerCase().includes(term));if(kind==='event')items.sort((a,b)=>Date.parse(a.start)-Date.parse(b.start));
 const root=$('results');root.replaceChildren();if(!items.length){root.append(el('p',t('ยังไม่มีประกาศในหมวดนี้ ร่วมส่งข้อมูลเพื่อเริ่มต้นเครือข่ายได้','No posts here yet. Contribute to help build the community.'),'empty'));return}
 for(const p of items){const c=el('article',undefined,'card');c.append(el('span',p.archived?t('ปิดแล้ว / คลังประกาศ','Closed / Archived'):t(...(categories[p.category]||kinds[p.kind])),'badge'),el('h3',p.title),el('p',p.institution+(p.location?' · '+p.location:''),'meta'));if(p.tags)c.append(el('p',p.tags,'meta'));if(p.deadline)c.append(el('p',t('ปิดรับ: ','Deadline: ')+p.deadline,'meta'));if(p.start)c.append(el('p',new Date(p.start).toLocaleString(lang==='th'?'th-TH':'en-GB',{timeZone:'Asia/Bangkok'})+t(' (เวลาไทย)',' (Bangkok time)'),'meta'));if(p.funding)c.append(el('p',t('ทุน/ค่าตอบแทน: ','Funding/pay: ')+p.funding));c.append(el('p',p.description,'description'));const actions=el('div',undefined,'actions');if(p.link)actions.append(link(p.link,t('รายละเอียด / สมัคร','Details / Apply')));actions.append(link('mailto:'+p.contact,t('ติดต่อ','Contact')),button(t('รายงานประกาศ','Report'),()=>report(p),true));if(p.kind==='event')actions.append(button(t('เพิ่มลงปฏิทิน','Add to calendar'),()=>calendar(p),true));c.append(actions);root.append(c)}
}
function field(form,label,name,value='',type='text',required=false){const l=el('label',label),i=el(type==='textarea'?'textarea':'input');if(type!=='textarea')i.type=type;i.name=name;i.value=value;i.required=required;i.maxLength=type==='textarea'?6000:2000;l.append(i);form.append(l);return i}
function access(){if(token)return editor();const w=workspace();w.append(el('h2',t('ขอสิทธิ์ลงประกาศ','Request posting access')),el('p',t('ผู้ดูแลจะตรวจสอบและส่งลิงก์ส่วนตัวให้ทางอีเมล ขั้นตอนนี้ยังไม่ส่งอีเมลอัตโนมัติ','An administrator will review your request and send a personal link by email. Email delivery is currently manual.')));const f=el('form');field(f,t('ชื่อ','Name'),'name','', 'text',true);field(f,t('อีเมล','Email'),'email','','email',true);consent(f,t('ยินยอมให้ผู้ดูแลใช้ข้อมูลเพื่อติดต่อเรื่องการลงประกาศ','I consent to administrator contact about posting access.'));submit(f,t('ส่งคำขอ','Send request'),async()=>{await request('/access',{...Object.fromEntries(new FormData(f)),consent:true});w.replaceChildren(el('p',t('ได้รับคำขอแล้ว ผู้ดูแลจะติดต่อกลับ','Request received. An administrator will contact you.')))});w.append(f)}
function consent(f,label){const l=el('label'),c=el('input');c.type='checkbox';c.required=true;l.append(c,document.createTextNode(label));f.append(l)}
function submit(f,label,fn){const b=el('button',label);b.type='submit';f.append(b);f.onsubmit=async e=>{e.preventDefault();b.disabled=true;try{await fn();notice('')}catch(err){notice(err.message)}finally{b.disabled=false}}}
function editor(post){const w=workspace(),p=post?JSON.parse(post.body):{},f=el('form');w.append(el('h2',post?t('แก้ไขประกาศ','Edit post'):t('สร้างประกาศ','Create a post')));const l=el('label',t('หมวดหมู่','Post type')),select=el('select');for(const [k,v] of Object.entries(kinds)){const o=el('option',t(...v));o.value=k;select.append(o)}select.value=post?.kind||kind;l.append(select);f.append(l);const fields=el('div');f.append(fields);
 const build=()=>{const saved={...p,...Object.fromEntries(new FormData(f))};fields.replaceChildren();field(fields,t('หัวข้อ / ชื่อแล็บ / ชื่อกิจกรรม','Title / Lab name / Event name'),'title',saved.title||'','text',true);field(fields,t('สถาบัน','Institution'),'institution',saved.institution||'','text',true);field(fields,t('สถานที่ / จังหวัด / ออนไลน์','Location / Province / Online'),'location',saved.location||'');field(fields,t('หัวข้อวิจัยหรือเทคนิค (คั่นด้วยจุลภาค)','Research topics or techniques (comma separated)'),'tags',saved.tags||'');field(fields,t('รายละเอียด','Description'),'description',saved.description||'','textarea',true);field(fields,t('อีเมลติดต่อที่จะเผยแพร่','Public contact email'),'contact',saved.contact||'','email',true);field(fields,t('ลิงก์รายละเอียดหรือสมัคร','Details or application URL'),'link',saved.link||'','url');if(select.value==='opportunity'){const l=el('label',t('ประเภทตำแหน่ง','Position type')),s=el('select');s.name='category';for(const [k,v] of Object.entries(categories)){const o=el('option',t(...v));o.value=k;s.append(o)}s.value=saved.category||'intern';l.append(s);fields.append(l);field(fields,t('ทุน / ค่าตอบแทน (ระบุหรือใส่ “ยังไม่ระบุ”)','Funding / Pay (or “Not specified”)'),'funding',saved.funding||'','text',true);field(fields,t('วันปิดรับ','Deadline'),'deadline',saved.deadline||'','date',true)}if(select.value==='event'){field(fields,t('เริ่ม (เวลาไทย)','Start (Bangkok time)'),'start',saved.start?bangkokInput(saved.start):'','datetime-local',true);field(fields,t('สิ้นสุด (เวลาไทย)','End (Bangkok time)'),'end',saved.end?bangkokInput(saved.end):'','datetime-local',true)}};select.onchange=build;build();consent(f,t('ยินยอมเผยแพร่ข้อมูลนี้และมีสิทธิ์ลงประกาศในนามสถาบัน การแก้ไขต้องตรวจรับใหม่','I consent to publication and am authorized to post for this institution. Edits require a new review.'));submit(f,t('ส่งให้ผู้ดูแลตรวจรับ','Submit for review'),async()=>{const b=Object.fromEntries(new FormData(f));if(select.value==='event'){b.start+=':00+07:00';b.end+=':00+07:00'}await request('/save',{...b,kind:select.value,consent:true,...(post?{id:post.id,revision:post.revision}:{})});w.replaceChildren(el('p',t('ส่งแล้ว อยู่ระหว่างรอตรวจรับ','Submitted for review.')));await load()});w.append(f)}
function bangkokInput(s){if(s.length===16)return s;return new Date(Date.parse(s)+7*3600000).toISOString().slice(0,16)}
async function myPosts(){try{const d=await request('/mine',{});mine=d.posts;const w=workspace();w.append(el('h2',t('ประกาศของ ','Posts by ')+d.name),button(t('สร้างประกาศ','Create post'),()=>editor()));const statuses={pending:['รอตรวจรับ','Pending'],approved:['เผยแพร่แล้ว','Published'],closed:['ปิดแล้ว','Closed'],withdrawn:['ถอนแล้ว','Withdrawn'],rejected:['ส่งกลับแก้ไข','Changes requested'],hidden:['ซ่อนโดยผู้ดูแล','Hidden']};for(const p of mine){const c=el('article',undefined,'card');c.append(el('h3',JSON.parse(p.body).title),el('p',t(...statuses[p.status])),el('p',p.reason),button(t('แก้ไข','Edit'),()=>editor(p)),button(t('ปิดประกาศ / ถอน','Close / Withdraw'),async()=>{try{await request('/close',{id:p.id});await load();await myPosts()}catch(e){notice(e.message)}},true));w.append(c)}}catch(e){notice(e.message)}}
function report(p){const w=workspace(),f=el('form');w.append(el('h2',t('รายงาน: ','Report: ')+p.title));field(f,t('เหตุผล (ไม่ใส่ข้อมูลส่วนตัว)','Reason (do not include personal data)'),'reason','','textarea',true);submit(f,t('ส่งรายงาน','Submit report'),async()=>{await request('/report',{id:p.id,reason:new FormData(f).get('reason')});w.replaceChildren(el('p',t('ส่งให้ผู้ดูแลแล้ว','Report sent to the administrator.')))});w.append(f)}
function calendar(p){const esc=s=>s.replace(/\\/g,'\\\\').replace(/\r?\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;'),date=s=>new Date(s).toISOString().replace(/[-:]/g,'').split('.')[0]+'Z';const content=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//ECS Thailand//Community//EN','BEGIN:VEVENT','UID:'+p.id+'@ecs-thai.github.io','DTSTAMP:'+date(new Date()),'DTSTART:'+date(p.start),'DTEND:'+date(p.end),'SUMMARY:'+esc(p.title),'LOCATION:'+esc(p.location),'DESCRIPTION:'+esc(p.description),'END:VEVENT','END:VCALENDAR'].join('\r\n');const u=URL.createObjectURL(new Blob([content],{type:'text/calendar;charset=utf-8'}));const a=el('a');a.href=u;a.download='ecs-event.ics';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
async function load(){const r=await fetch(api+'/posts');if(!r.ok)throw Error(t('โหลดข้อมูลไม่ได้','Could not load posts'));posts=(await r.json()).posts;render()}
$('language').onclick=()=>{lang=lang==='th'?'en':'th';render();$('workspace').hidden=true};$('contribute').onclick=access;$('mine').onclick=myPosts;$('logout').onclick=()=>{token='';sessionStorage.removeItem('ecs-community-access');$('workspace').hidden=true;render()};$('search').oninput=list;$('category').onchange=list;$('archive').onchange=list;
(async()=>{try{token=new URLSearchParams(location.hash.slice(1)).get('access')||sessionStorage.getItem('ecs-community-access')||'';if(location.hash){history.replaceState(null,'',location.pathname);sessionStorage.setItem('ecs-community-access',token)}api=(await (await fetch('config.json')).json()).apiBase;await load()}catch(e){notice(t('โหลดชุมชนไม่ได้ กรุณาลองใหม่ภายหลัง','Could not load the community. Please retry later.'))}})();
